name: Create Branch on Issue Assignment

on:
  issues:
    types: [assigned]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Branch
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_BRANCH="feature/issue-${ISSUE_NUMBER}"
        git checkout develop
        git checkout -b $ISSUE_BRANCH
        git push origin $ISSUE_BRANCH
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
