name: Delete Branch after Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Delete branch
      run: |
        BRANCH=${{ github.event.pull_request.head.ref }}
        if [[ $BRANCH == feature/* ]]; then
          git push origin --delete $BRANCH
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
