name: Conventional Commits

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Conventional Commits
        uses: conventional-changelog/commitlint-action@v3
