name: Conventional Commits

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Conventional Commits
      uses: commit-check/commit-check-action@v1
      with:
          message: true
          branch: true
          author-name: true
          author-email: true
          commit-signoff: true
          dry-run: false
          job-summary: true
