name: Conventional Commits

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Conventional Commits
      uses: amannn/action-semantic-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
