name: Conventional Commits

on:
  push:
    branches:
      - 'features/*'
      - 'hotfix/*'

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Conventional Commits
      uses: webiny/action-conventional-commits@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
